apiVersion: v1
kind: Namespace
metadata:
  name: application-alpha
---
apiVersion: application.sample.ibm.com/v1alpha1
kind: Application
metadata:
  name: application
  namespace: application-alpha
spec:
  version: "1.0.0"
  amountPods: 1
  databaseName: database
  databaseNamespace: database
  image: docker.io/nheidloff/simplemicroservice:v1.0.59

